Webservice/Controllers/SellerController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.Dto.Request;
using Service.Dto.Request.Admin;
using Service.Dto.Response;
using Service.Interface;
using Webservice.Helper;

namespace Webservice.Controllers
{
    [Authorize]
    public class SellerController : Controller
    {
        private readonly CookieUserDetailsHandler cookieUserDetailsHandler;
        private readonly ISellerService sellerService;
        public SellerController(CookieUserDetailsHandler cookieUserDetailsHandler, ISellerService sellerService)
        {
            this.cookieUserDetailsHandler = cookieUserDetailsHandler;
            this.sellerService = sellerService;
        }
        public IActionResult SendRequest()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendRequest(SellerRequestDto dto)
        {
            dto.Requestor = await cookieUserDetailsHandler.GetUserDetail(this.User.Identity as ClaimsIdentity);
            var data = await sellerService.Request(dto);

            TempData["apiResponseMessage"] = data.Message;
            TempData["apiResponseStatusCode"] = data.StatusCodes.ToString();

            if (data.Result is not null)
            {
                return View("ViewRequest", (SellerRequestResponse)data.Result);
            }

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Update(UpdateSellerRequestStatus dto)
        {
            dto.Requestor = await cookieUserDetailsHandler.GetUserDetail(this.User.Identity as ClaimsIdentity);
            await sellerService.UpdateRequestStatus(dto);

            return RedirectToAction("SellerRequests", "Admin");
        }
        public async Task<IActionResult> ViewRequest()
        {
            var requestor = await cookieUserDetailsHandler.GetUserDetail(this.User.Identity as ClaimsIdentity);
            var data = await sellerService.Get(requestor);
            return View((SellerRequestResponse)data.Result);
        }
    }
}

Webservice/Views/Seller/SendRequest.cshtml
@using Entities.Models
@model Service.Dto.Request.SellerRequestDto;

@Html.Partial("_PopAlert");

<form class="max-w-md mx-auto" asp-action="SendRequest" asp-controller="Seller" method="post">
    <div class="relative z-0 w-full mb-5 group">
        <input asp-for="StoreName" type="text" name="StoreName" id="floating_email"
            class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
            placeholder=" " required />
        <label for="floating_email"
            class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">store
            name</label>
    </div>
    <div class="grid md:grid-cols-2 md:gap-6">
        <div class="relative z-0 w-full mb-5 group">
            <input asp-for="StoreAddress" type="text" name="StoreAddress" id="StoreAddress"
                class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                placeholder=" " required />
            <label for="floating_first_name"
                class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">store
                address</label>
        </div>
    </div>
    <div class="grid md:grid-cols-2 md:gap-6">
        <div class="relative z-0 w-full mb-5 group">
            <input asp-for="StoreContactNumber" type="tel" name="StoreContactNumber" id="floating_phone"
                class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                placeholder=" " required />
            <label for="floating_phone"
                class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Store
                Phone</label>
        </div>

        <select asp-for="PaymentMethod" class="form-control">
            <option value="">Select Payment Method</option>
            @foreach (var method in Enum.GetValues(typeof(PaymentMethod)))
            {
                <option value="@method">@method</option>
            }
        </select>

    </div>
    <button type="submit"
        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
</form>

Webservice/Views/Seller/ViewRequest.cshtml
@model Service.Dto.Response.SellerRequestResponse;

<div class="storeheader">
    <h1>
        Store Info
    </h1>
</div>


<div class="maincontainer">
    <a href="#"
        class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Store Name : @Model.StoreName
        </h5>
        <p class="font-normal text-gray-700 dark:text-gray-400">Store Address : @Model.StoreAddress</p>
        <p class="font-normal text-gray-700 dark:text-gray-400">Store ContactNumber : @Model.StoreContactNumber</p>
        <p class="font-normal text-gray-700 dark:text-gray-400">Payment Method : @Model.PaymentMethod</p>
        <p class="font-normal text-gray-700 dark:text-gray-400">Request Status : @Model.Status</p>
    </a>
</div>


<style>
    .maincontainer {
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .storeheader {
        display: flex;
        align-items: center;
        justify-content: center;
    }
</style>